### PR TITLE
update parquet format to 2.6.0

### PR DESCRIPTION
**Pull request by nevi-me**
I've updated the parquet version to 2.6.0 (took it from the 2.6.0 release on pq-format, and not master).

I'm on windows, so my thrift executable's still `0.11.0`, I saw that the previous version was compiled with `1.0.0-dev`, don't know if that's an issue? I think it might be the reason why `#[derive(..., Hash, ...)]`

### CODE REVIEW

**Comment by sunchao** [comment]
Thanks. Should we upgrade to 2.5.0 before moving to 2.6.0? We should do two releases so `parquet-rs` can depend on 2.5.0 first and then 2.6.0.

**Comment by nevi-me** [comment]
I thought of that, but was unsure of how to proceed. I can submit a separate PR for 2.5, then rebase(?) 2.6 against it.

**Comment by sunchao** [comment]
Yes you can submit for 2.5.0. After that's merged we'll do a release. Then you can proceed with 2.6.0. :)

**Comment by nevi-me** [comment]
done @sunchao

**Comment by sunchao** [comment]
@nevi-me : could you rebase this PR?

**Comment by sunchao** [comment]
Merged. Thanks @nevi-me .

**Pull request merged**
