### PR TITLE
Format 2.8.0

### PR DESCRIPTION
**Pull request by nevi-me**
Adds support for version 2.8.0 of the Parquet format

### CODE REVIEW

**Review by sadikovi — APPROVED** [review]
LGTM.

**Comment by mispecto** [comment]
Hi! Is there anything that prevents from these patches (updating Parquet format) to be merged in?

**Comment by sunchao** [comment]
My apologies for the very long delay!!! I wasn't notified by this PR and the others (somehow I was not watching this repo). @nevi-me do you mind to resolve the conflict? I can help merging this.

**Comment by nevi-me** [comment]
Sorry @sunchao, I forgot to rebase. I see you've opened a separate PR, I'll close this one.

**Comment by sunchao** [comment]
no worries - can you check if the other one is OK? I'll merge & publish a new version afterwards.

**Pull request closed without merging**
