### PR TITLE
Update to thrift 0.13, use 2018 edition

### PR DESCRIPTION
**Pull request by nevi-me**
Thrift 0.13 removed `try_from` and re-exported `ordered-float`, so I've rebuilt the thrift file and updated the code to remove the 2 dependencies.

@sunchao @sadikovi PTAL, CC @andygrove

### CODE REVIEW

**Review by sadikovi — APPROVED** [review]
LGTM.

**Comment by ccakes** [comment]
Is there an ARROW JIRA issue for this? Just looking for info why it might not be merged yet..

**Comment by sunchao** [comment]
@ccakes sorry for being late - just merged.

**Comment by houqp** [comment]
@sunchao any plan to release a new version of the crate for this change?

**Comment by alamb** [comment]
@sunchao  I agree it would be great to get this change released. Can we help in some way?

**Comment by sunchao** [comment]
@houqp @alamb created #12 for this. Could you review the PR?

**Comment by sunchao** [comment]
Released version 2.6.1 with thrift 0.13 support.

**Pull request merged**
