### PR TITLE
Format 2.7.0

### PR DESCRIPTION
**Pull request by nevi-me**
Adds support for version 2.7.0 of the Parquet format

### CODE REVIEW

**Comment by nevi-me** [comment]
@sunchao is there value in releasing 2.7.0 then 2.8.0 sequentially? If so, I'll rebase this PR

**Comment by nevi-me** [comment]
I've rebased @sunchao

**Comment by sunchao** [comment]
@nevi-me with #13 I'm not sure if this is still required since currently we only support a single Parquet version.

**Comment by sunchao** [comment]
Actually @nevi-me NVM the above is not true - we should publish 2.7.0 first followed by 2.8.0

**Comment by nevi-me** [comment]
My intention is to complete 2.6.0 support (to the extent that it's not all supported) in arrow/parquet, then move to 2.7 and 2.8 incrementally.

**Review by sunchao — APPROVED** [review]
+1

**Comment by sunchao** [comment]
new version published: https://crates.io/crates/parquet-format

**Pull request merged**
